# Generated by Django 2.0.5 on 2018-05-08 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('message', models.TextField()),
                ('item', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
